site_name: BGE Lesson Files

nav:
    - Home: 'index.md'
    - Term 2 - Game Design:
      - SDD/index.md
      - Development Methodologies: 'SDD/01-Development-Methodologies.md'
      - Analysis: 'SDD/02-Analysis.md'
      - Design: 'SDD/03-Design.md'
      - Software Implementation: 'SDD/04-Software-Implementation.md'


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
theme:
  name: material
  font:
    text: Quicksand
  palette: 
    - scheme: slate
      toggle:
       icon: material/weather-sunny
       name: Dark mode
      primary: green
      accent: deep purple

    - scheme: default
      toggle:
       icon: material/weather-night
       name: Light mode
      primary: blue
      accent: deep orange
